LOAN/urls.py
from django.contrib import admin
from django.urls import path
from loanapp.views import homepage, AddClient, ClientList, ClientDisplay, ClientUpdate, ClientDelete, CollateralDisplay 
from loanapp import views



urlpatterns = [
    path('admin/', admin.site.urls),
     #path('', views.homepage, name='homepage'),
    path('', homepage.as_view(), name='homepage'),
    #path('addclient/', AddClient.as_view(), name='add_client'),
    path('addclient/', AddClient.as_view(), name='add_client'),
    path('clientlist/', ClientList.as_view(), name='clientlist' ),
    path('clientdisplay/<int:pk>', ClientDisplay.as_view(), name='clientdisplay'),
    path('clientupdate/<int:pk>',ClientUpdate.as_view(), name='clientupdate'),
    path('clientdelete/<int:pk>', ClientDelete.as_view(), name='clientdelete'),
    path('collateral/', views.CollateralDisplay, name='collateral'),
    
]

loanapp/models.py
from django.db import models

# Create your models here.

FORM_CHOICES= [("Sole Prorprietorship", "Sole Proprietorship"),
               ("Private Limited", "Private Limited"),
               ("Corporation", "Corporation"),
               ("Partnership", "Partnership"),
               ("Limited Liability Company", "Limited Liability Company")]

class ClientDetail(models.Model):
    name= models.CharField(max_length=300)
    address= models.CharField(max_length=150)
    vdc= models.CharField(max_length=100, null=True, blank=True)
    vdc_date= models.CharField(max_length=12, null=True, blank=True)
    iro_address= models.CharField(max_length=50)
    iro_date= models.CharField(max_length=12)
    smi_address= models.CharField(max_length=50)
    smi_date= models.CharField(max_length=12)
    capital= models.CharField(max_length=20)
    capital_new= models.CharField(max_length=20, null=True, blank=True, default='') 
    
    # Firm Related 
    pro_name= models.CharField(max_length=100)
    firm_type= models.CharField(max_length=100, choices=FORM_CHOICES)
    exp_year= models.CharField(max_length=5, null=True, default='', blank=True)
    pre_sales= models.CharField(max_length=6, null=True, default='', blank=True)
    pre_networth= models.CharField(max_length=6, null=True, default='', blank=True)
    cur_sales= models.CharField(max_length=6, null=True, default='', blank=True)
    cur_networth= models.CharField(max_length=6, null=True, default='', blank=True)
    business_type= models.CharField(max_length=100, null=True, default='', blank=True)
    product= models.CharField(max_length=100, null=True, default='', blank=True)
    product_types= models.CharField(max_length=100, null=True, default='', blank=True)
    brand= models.CharField(max_length=100, default='', blank=True, null= True)
    brand_types= models.CharField(max_length=100, default='', blank=True, null=True)
   
    
    def __str__(self):
        return self.name 

class Collateral(models.Model):
    plot_no= models.CharField(max_length=30)
    plot_owner= models.CharField(max_length=100)
    plot_add= models.CharField(max_length=150)
    valuator= models.CharField(max_length=100)
    distress_amt= models.FloatField(max_length=50)
    margin= models.FloatField(max_length=50)
    mortgaged_amt= models.FloatField(max_length=50, null= True, blank= True)
    
    building_value= models.FloatField(max_length=5, null=True, blank= True)
    building_storey=models.CharField(max_length=10, null=True, blank= True)
    
    def __str__(self):
        return self.plot_owner 

loanapp/forms.py
from django import forms 
from .models import ClientDetail, Collateral

class ClientDetailForm(forms.ModelForm):
    
    class Meta: 
        model= ClientDetail
        fields= '__all__' 
        
class CollateralForm(forms.ModelForm):
    class Meta:
        model= Collateral 
        fields= '__all__'        

loanapp/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import CreateView 
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from .models import ClientDetail, Collateral
from .forms import ClientDetailForm, CollateralForm
from django.contrib.messages.views import SuccessMessageMixin
# Create your views here.


class homepage(TemplateView):
    template_name="base.html"
    
class AddClient(SuccessMessageMixin, CreateView):
    model= ClientDetail
    fields=['name','address','iro_address', 'iro_date','smi_address','smi_date','capital','capital_new',
            'pro_name','firm_type','exp_year','pre_sales','pre_networth','cur_sales','cur_sales','cur_networth'
            ,'business_type','product','product_types','brand','brand_types']   
    
    template_name='add_client.html' 
    success_url='/addclient/' 
    success_message="1 Client(s) added Successfully !!!"
    
class ClientList(ListView):
    model= ClientDetail
    template_name= 'client_list.html'      
    
#Display client details via DetailView    
class ClientDisplay(DetailView):
    model=ClientDetail
    template_name='client_display.html'
    
    
class ClientUpdate(UpdateView):
    model= ClientDetail 
    form_class= ClientDetailForm 
    template_name= 'client_update.html' 
    success_url= '/clientlist/'    

class ClientDelete(DeleteView):
    model= ClientDetail 
    template_name= 'client_delete.html'    
    success_url= '/clientlist/'
    

def CollateralDisplay(request):
    plot_no= plot_add= plot_owner=valuator= builidng_storey= ''
    distress_amt= mortgaged_amt= margin= building_value= total_amt= proposed_amt= old_margin= 0.0
    flag= None
    form= CollateralForm()
    if request.method=='POST':
        form= CollateralForm(request.POST)
        if form.is_valid():
            plot_no= form.cleaned_data['plot_no']
            plot_owner= form.cleaned_data['plot_owner']
            plot_add= form.cleaned_data['plot_add']
            valuator= form.cleaned_data['valuator']
            distress_amt= form.cleaned_data['distress_amt']
            margin= form.cleaned_data['margin']
            mortgaged_amt= form.cleaned_data['mortgaged_amt']
            building_value= form.cleaned_data['building_value']
            builidng_storey= form.cleaned_data['building_storey']
            
            if (building_value and plot_no):
                total_amt= float(distress_amt) + float(building_value)
                temp= (100.0-margin)
                proposed_amt= ((total_amt*temp)/100)
                proposed_amt= round(proposed_amt,2)
                flag=True 
            elif (mortgaged_amt):
                total_amt= float(distress_amt)
                old_margin= float((mortgaged_amt*100)/distress_amt)
                old_margin= round(old_margin,2)
                flag=False
            else:
                total_amt= distress_amt
                temp= (100.0-margin)
                proposed_amt= ((total_amt*temp)/100)
                proposed_amt= round(proposed_amt,2)
                flag=None
            
        else:
            form= CollateralForm()
    return render(request, 'collateral.html', {'form':form, 'plot_no':plot_no, 'plot_owner':plot_owner, 'plot_add':plot_add,
                                               'valuator':valuator, 'distress_amt':distress_amt, 'margin':margin,
                                               'mortgaged_amt':mortgaged_amt, 'building_value':building_value, 
                                               'building_storey':builidng_storey, 'total_amt':total_amt, 
                                               'proposed_amt':proposed_amt, 'flag':flag, 'old_margin':old_margin})            
        
        
        
    
    

templates/add_client.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  AddClient
{% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/add_client.css' %} " />
{% endblock css %}

{% block bodycontent %}
  <div class="container my-4">
    <form action="" method="POST">
      {% csrf_token %}

      <div class="row border border-primary p-3">
        <div class="col mb-3">
          <p class="text-center text-danger mt-2">Borrower/Location/Establishment</p>
          <hr color="red" />
          <p>
            <label for="id_name">Nam of Firm:</label>
            <input type="text" name="name" maxlength="300" required id="id_name" />
          </p>
          <p>
            <label for="id_address">Firm Address:</label>
            <input type="text" name="address" maxlength="150" required id="id_address" />
          </p>
          <p>
            <label for="id_iro_address">Inland Revenue:</label>
            <input type="text" name="iro_address" maxlength="50" required id="id_iro_address" />
          </p>
          <p>
            <label for="id_iro_date">Inland Revenue Reg. Date:</label>
            <input type="text" name="iro_date" maxlength="12" required id="id_iro_date" />
          </p>
          <p>
            <label for="id_smi_address">Firm Darta:</label>
            <input type="text" name="smi_address" maxlength="50" required id="id_smi_address" />
          </p>
          <p>
            <label for="id_smi_date">Firm Darta ate:</label>
            <input type="text" name="smi_date" maxlength="12" required id="id_smi_date" />
          </p>
        </div>
        <div class="col">
          <p class="text-center text-danger mt-2">Firm/Business/Detail</p>
          <hr color="red" />
          <p>
            <label for="id_capital">Initial Capital:</label>
            <input type="text" name="capital" maxlength="20" required id="id_capital" />
          </p>
          <p>
            <label for="id_capital_new">New Capital(Optional):</label>
            <input type="text" name="capital_new" maxlength="20" id="id_capital_new" />
          </p>
          <p>
            <label for="id_pro_name">Pro. Name:</label>
            <input type="text" name="pro_name" maxlength="100" required id="id_pro_name" />
          </p>
          <p>
            <label for="id_firm_type">Firm type:</label>
            <select name="firm_type" required id="id_firm_type">
              <option value="" selected>---------</option>

              <option value="Sole Prorprietorship">Sole Proprietorship</option>

              <option value="Private Limited">Private Limited</option>

              <option value="Corporation">Corporation</option>

              <option value="Partnership">Partnership</option>

              <option value="Limited Liability Company">Limited Liability Company</option>
            </select>
          </p>

          <p>
            <label for="id_exp_year">Exp year(In Years):</label>
            <input type="text" name="exp_year" maxlength="5" id="id_exp_year" />
          </p>

          <p>
            <label for="id_pre_sales">Previous sales(million):</label>
            <input type="text" name="pre_sales" maxlength="6" id="id_pre_sales" />
          </p>

          <p>
            <label for="id_pre_networth">Previous Networth(million):</label>
            <input type="text" name="pre_networth" maxlength="6" id="id_pre_networth" />
          </p>
        </div>
        <div class="col">
          <p class="text-center text-danger mt-2">Nature of Business/Items</p>
          <hr color="red" />

          <p>
            <label for="id_cur_sales">Current Sales:</label>
            <input type="text" name="cur_sales" maxlength="6" id="id_cur_sales" />
          </p>

          <p>
            <label for="id_cur_networth">Current Networth:</label>
            <input type="text" name="cur_networth" maxlength="6" id="id_cur_networth" />
          </p>

          <p>
            <label for="id_business_type">Business type:</label>
            <input type="text" name="business_type" maxlength="100" id="id_business_type" />
          </p>

          <p>
            <label for="id_product">Product(Optional):</label>
            <input type="text" name="product" maxlength="100" id="id_product" />
          </p>

          <p>
            <label for="id_product_types">Product types(Optional):</label>
            <input type="text" name="product_types" maxlength="100" id="id_product_types" />
          </p>

          <p>
            <label for="id_brand">Brand(Optional):</label>
            <input type="text" name="brand" maxlength="100" id="id_brand" />
          </p>

          <p>
            <label for="id_brand_types">Brand types(Optional):</label>
            <input type="text" name="brand_types" maxlength="100" id="id_brand_types" />
          </p>
          <input type="submit" class="btn btn-primary submit-btn fs-6" value="Submit" />
        </div>
      </div>
    </form>
    {% if messages %}
      {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}" id="msg">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}
  </div>
  <script>
    var message_ele = document.getElementById("msg");
        setTimeout(function() {
        message_ele.style.display = "none";
      }, 3000);

</script>
{% endblock %}

templates/add_client1.html
{% extends 'base.html' %}
{% load static %}
{% block title %} AddClient {% endblock title %}
{% block css %}  <link rel="stylesheet" href="{% static 'css/add_client.css' %} "> {% endblock css %}

{% block bodycontent %}

    <div class="container my-4">
       <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}} 
        <input type="submit" value="Submit">
    </div>

{% endblock bodycontent %}

templates/add_client2.html
{% extends 'base.html' %}
{% load static %}
{% block title %} AddClient {% endblock title %}
{% block css %}  <link rel="stylesheet" href="{% static 'css/add_client.css' %} "> {% endblock css %}

{% block bodycontent %}
<div class="container my-4">
    <form class="row g-3"action="" method="post">
        {% csrf_token %} 
    <div class="row border border-primary">
      <div class="col mb-3">
        <p class="text-center text-danger mt-2">Borrower/Location/Establishment</p>
            <hr color="red">
        <label for="id_name">Name of Firm:</label><br>
        <input type="text" name="name" class="" maxlength="300"  required id="id_name" style="width: 200px";><br>
        <label for="id_pro_name">Name of Proprietor:</label><br>
        <input type="text" name="pro_name" maxlength="200" required id="id_pro_name" style="width: 200px";> <br>
        <label for="id_address">Address of Firm:</label> <br>
        <input type="text" name="address" class="" maxlength="150" required id="id_address" style="width: 200px";>  <br>                      
        <label for="id_iro_address">PAN Registered Location:</label><br>
        <input type="text" name="iro_address" class="" maxlength="50" required id="id_iro_address"style="width: 200px";><br>
        <label for="id_iro_date">PAN Registered Date:</label><br>
        <input type="text" name="iro_date" class="" maxlength="15" required id="id_iro_date"style="width: 200px";><br>
        <label for="id_smi_address">Gharelu Registered Location:</label><br>
        <input type="text" name="smi_address" class="" maxlength="150"  id="id_smi_address"style="width: 200px";><br>          
        <label for="id_smi_date">Gharelu Registered date:</label><br>
        <input type="text" name="smi_date" class="" maxlength="15" required id="id_smi_date"style="width: 200px";> <br>                     
      </div>
      
      <div class="col">
        <p class="text-center text-danger mt-2">Firm/Business/Detail</p>
        <hr color="red">
            
        <label for="capital">Registered Capital Amount(In Million):</label><br>
        <input type="text" name="capital" class="text-danger" maxlength="20" required id="id_capital"style="width: 200px";><br>
        <label for="capital_new">New Capital Amount(In Million)[Optonal]:</label><br>
        <input type="text" name="capital_new" id="id_capital_new"style="width: 200px";><br>   
        <label for="exp_year">Experience Year:</label><br>
        <input type="text" name="exp_year" id="exp_year"style="width: 200px";><br> 
        <label for="pre_sales">Last Year Sales(In Million):</label><br>
        <input type="text" name="pre_sales" id="pre_sales"style="width: 200px";><br>
        <label for="pre_networth">Last Year Networth(In Million):</label><br>
        <input type="text" name="pre_networth" id="pre_networth"style="width: 200px";><br>
        <label for="cur_sales">Current Year Sales(In Million):</label><br>
        <input type="text" name="cur_sales" id="cur_sales"style="width: 200px";><br>
        <label for="cur_networth">Current Year Networth(In Million):</label><br>
        <input type="text" name="cur_networth" id="cur_networth"style="width: 200px";><br>
      </div>

      <div class="col">
        <p class="text-center text-danger mt-2">Nature of Business/Items</p>
            <hr color="red">
         
            <label for="firm_type">Firm Nature:</label><br>
            <select required id="firm_type" name="firm_type">
              <option value="Sole Propreitorship">Sole Propreitorship</option>
              <option value="Private Limited">Private Limited</option>
              <option value="Corporation">Corporation</option>
              <option value="Partnership">Partnership</option>
              <option value="Limited Liability Company">Limited Liability Company</option>
            </select>
            <br>                                    
            <label for="Business_type">Business Type:</label><br>
            <input type="text" name="business_type" required maxlength="200"  id="Business_type"style="width: 200px";> <br>                          
            <label for="product">Product:</label><br>
            <input type="text" name="product"  maxlength="100" id="product"style="width: 200px";><br>                 
            <label for="product_types">Product Types:</label><br>
            <input type="text" name="product_types"  maxlength="100" id="product_types"style="width: 200px";><br>                 
            <label for="brand">Brand (Optional):</label><br>
            <input type="text" name="brand"  maxlength="50" id="brand"style="width: 200px";><br>                   
            <label for="brand_types">Brand Products (Optional):</label><br>
            <input type="text" name="brand_types"  maxlength="100" id="brand_types"style="width: 200px";><br>   
             
      </div>
    </div>
    <input type="submit" value="Submit" class="btn btn-success">
    </form>
</div>

{% endblock bodycontent %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block title %}
        BasePage
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    {% block css %}  {% endblock css %}
  </head>
  <body>
    <!-- navbar start -->
    
            <div class="container-fluid">
        <div class="row">
         <div class="row1">
             <div class="intro-text">
                 <p class="text-center fs-5 text-danger">Loan Automation System</p>
             </div>
         </div>
         <div class="row2">
             <ul class="nav justify-content-center d-flex">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage' %}">Homepage</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_client' %}">Add Client</a>
              </li>
                 <li class="nav-item">
                   <a class="nav-link" href="{% url 'clientlist' %}">Customer List</a>
                 </li>
                 <li class="nav-item">
                   <a class="nav-link" href="{% url 'collateral' %}">Collateral Details</a>
                 </li>
               </ul>
         </div>
        </div>
     </div>

    <!-- End of navbar start -->

    <div class="body-section py-6">
      {% block bodycontent %}
      <div class="container text-center">
        <img src="{% static 'images/loan1.jpg' %}" class="img-fluid mt-5" alt="loan automtion">

      </div>

      {% endblock bodycontent %}
    </div>

    <!--footer section-->
     
    {% include 'footer.html' %}
   

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

templates/client_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ClientList {% endblock title %}

{% block bodycontent %}

<div class="container text-center">
 <p>Do you want to Delete?</p>
 <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <a href="{% url 'clientlist' %}">Cancel</a>
 </form>

</div>



{% endblock bodycontent %}

templates/client_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ClientList {% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/client_list.css' %} " />
{% endblock css %}
{% block bodycontent %}

<div class="container">
  {% if object_list %}
    <table class="table">
        <thead>
            <th>SN</th>
            <th>Name of Firm</th>
            <th>Address</th>
            <th>Action</th>
            </tr>
        </thead>
    {% for ClientDetail in object_list %}
     <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{ClientDetail.name}}</td>
        <td>{{ClientDetail.address}}</td>
        <td>
            <a href="{% url 'clientdisplay' ClientDetail.pk %}" class="button bg-primary">View</a>
            <a href="{% url 'clientupdate' ClientDetail.pk %}" class="button bg-success">Update</a>
            <a href="{% url 'clientdelete' ClientDetail.pk %}" class="button bg-danger">Delete</a></td>
     </tr>
    {% endfor %}
</table>
  {% else %}  
    <h3>No Client has been Added</h3>
    <a href="{% url 'add_client' %}">Add New Client</a>
  {% endif %}

</div>



{% endblock bodycontent %}

templates/client_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ClientUpdate {% endblock title %}
{% block css %} <link rel="stylesheet" href="{% static 'css/client_update.css' %}"/> {% endblock css %}
{% block bodycontent %}
<div class="container text-center">
    <h4 class="text-danger text-decoration-underline">Update Record</h4>
    <div class="text-center p-3">
      <form action="" class="mx-auto update-form border border-primary py-3" method="POST">
        {% csrf_token %} 
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-danger">
    </form>
    </div>

</div>
                                           
{% endblock bodycontent %}

templates/client_update2.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ClientUpdate {% endblock title %}

{% block bodycontent %}

<div class="container my-4">
    <form class="row g-3"action="" method="POST">
        {% csrf_token %} 
    <div class="row border border-primary">
      <div class="col mb-3">
        <p class="text-center text-danger mt-2">Borrower/Location/Establishment</p>
            <hr color="red">
        <label for="id_name">Name of Firm:</label><br>
        <input type="text" name="name" class="" maxlength="300" value="{{object.name}}" id="id_name" style="width: 200px";><br>
        <label for="id_pro_name">Name of Proprietor:</label><br>
        <input type="text" name="pro_name" maxlength="200" value="{{object.pro_name}}" id="id_pro_name" style="width: 200px";> <br>
        <label for="id_address">Address of Firm:</label> <br>
        <input type="text" name="address" class="" maxlength="150" value="{{object.address}}" id="id_address" style="width: 200px";>  <br>                      
        <label for="id_iro_address">PAN Registered Location:</label><br>
        <input type="text" name="iro_address" class="" maxlength="50" value="{{object.iro_address}}" id="id_iro_address"style="width: 200px";><br>
        <label for="id_iro_date">PAN Registered Date:</label><br>
        <input type="text" name="iro_date" class="" maxlength="15" value="{{object.iro_date}}" id="id_iro_date"style="width: 200px";><br>
        <label for="id_smi_address">Gharelu Registered Location:</label><br>
        <input type="text" name="smi_address" class="" maxlength="150" value="{{object.smi_date}}" id="id_smi_address"style="width: 200px";><br>          
        <label for="id_smi_date">Gharelu Registered date:</label><br>
        <input type="text" name="smi_date" class="" maxlength="15" value="{{object.id_smi}}" id="id_smi_date"style="width: 200px";> <br>                     
      </div>
      
      <div class="col">
        <p class="text-center text-danger mt-2">Firm/Business/Detail</p>
        <hr color="red">
            
        <label for="capital">Registered Capital Amount(In Million):</label><br>
        <input type="text" name="capital" class="text-danger" maxlength="20" value="{{object.capital}}" id="id_capital"style="width: 200px";><br>
        <label for="capital_new">New Capital Amount(In Million)[Optonal]:</label><br>
        <input type="text" name="capital_new" value="{{object.capital_new}}" id="id_capital_new"style="width: 200px";><br>   
        <label for="exp_year">Experience Year:</label><br>
        <input type="text" name="exp_year" value="{{object.exp_year}}" id="exp_year"style="width: 200px";><br> 
        <label for="pre_sales">Last Year Sales(In Million):</label><br>
        <input type="text" name="pre_sales" value="{{object.pre_sales}}" id="pre_sales"style="width: 200px";><br>
        <label for="pre_networth">Last Year Networth(In Million):</label><br>
        <input type="text" name="pre_networth" value="{{object.pre_networth}}" id="pre_networth"style="width: 200px";><br>
        <label for="cur_sales">Current Year Sales(In Million):</label><br>
        <input type="text" name="cur_sales" value="{{object.cur_sales}}" id="cur_sales"style="width: 200px";><br>
        <label for="cur_networth">Current Year Networth(In Million):</label><br>
        <input type="text" name="cur_networth" value="{{object.cur_networth}}" id="cur_networth"style="width: 200px";><br>
      </div>

      <div class="col">
        <p class="text-center text-danger mt-2">Nature of Business/Items</p>
            <hr color="red">
         
            <label for="firm_type">Firm Nature:</label><br>
            <select value="{{object.firm_type}}" id="firm_type" name="firm_type">
              <option value="Sole Propreitorship">Sole Propreitorship</option>
              <option value="Private Limited">Private Limited</option>
              <option value="Corporation">Corporation</option>
              <option value="Partnership">Partnership</option>
              <option value="Limited Liability Company">Limited Liability Company</option>
            </select>
            <br>                                    
            <label for="Business_type">Business Type:</label><br>
            <input type="text" name="business_type"  maxlength="200" value="{{object.business_type}}" id="Business_type"style="width: 200px";> <br>                          
            <label for="product">Product:</label><br>
            <input type="text" name="product"  maxlength="100" value="{{object.product}}" id="product"style="width: 200px";><br>                 
            <label for="product_types">Product Types:</label><br>
            <input type="text" name="product_types"  maxlength="100" value="{{object.product_types}}" id="product_types"style="width: 200px";><br>                 
            <label for="brand">Brand (Optional):</label><br>
            <input type="text" name="brand"  maxlength="50" value="{{object.brand}}" id="brand"style="width: 200px";><br>                   
            <label for="brand_types">Brand Products (Optional):</label><br>
            <input type="text" name="brand_types"  maxlength="100" value="{{object.brand_types}}" id="brand_types"style="width: 200px";><br>   
             
      </div>
    </div>
    <input type="submit" value="Submit" class="btn btn-success">
    </form>
</div>


                                           
{% endblock bodycontent %}

templates/dashboard.html
{% extends 'base.html' %}

{% block title %} Dashboard {% endblock title %}

{% block bodycontent %}

<div class="container">
    
   
</div>
   
{% endblock bodycontent %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %} AddClient {% endblock title %}
{% block css %}  <link rel="stylesheet" href="{% static 'css/add_client.css' %} "> {% endblock css %}

{% block bodycontent %}

    <div class="container my-4">
        <form class="row g-3"action="{% url 'client_update' client.id %}" method="post">
            {% csrf_token %} 
        <div class="row border border-primary">
          <div class="col mb-3">
            <p class="text-center text-danger mt-2">Borrower/Location/Establishment</p>
                <hr color="red">
            <label for="id_name">Name of Firm:</label><br>
            <input type="text" name="name" value="" class="" maxlength="300"  id="id_name" style="width: 200px";><br>
            <label for="id_pro_name">Name of Proprietor:</label><br>
            <input type="text" name="pro_name" maxlength="200"  id="id_pro_name" style="width: 200px";> <br>
            <label for="id_address">Address of Firm:</label> <br>
            <input type="text" name="address" class="" maxlength="150"  id="id_address" style="width: 200px";>  <br>                      
            <label for="id_iro_address">PAN Registered Location:</label><br>
            <input type="text" name="iro_address" class="" maxlength="50"  id="id_iro_address"style="width: 200px";><br>
            <label for="id_iro_date">PAN Registered Date:</label><br>
            <input type="text" name="iro_date" class="" maxlength="15"  id="id_iro_date"style="width: 200px";><br>
            <label for="id_smi_address">Gharelu Registered Location:</label><br>
            <input type="text" name="smi_address" class="" maxlength="150"  id="id_smi_address"style="width: 200px";><br>          
            <label for="id_smi_date">Gharelu Registered date:</label><br>
            <input type="text" name="smi_date" class="" maxlength="15"  id="id_smi_date"style="width: 200px";> <br>                     
          </div>
          
         
        </div>
        <input type="submit" value="Submit" class="btn btn-success">
        </form>
    </div>

{% endblock bodycontent %}

templates/footer.html
<div class="footer text-center">
    <p class="">copyright@ChamlingTECH </p>

  </div>

templates/update1.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ClientUpdate {% endblock title %}

{% block bodycontent %}
<div class="container">
    <h3>Update Record</h3>
<form action="" method="POST">
    {% csrf_token %} 
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-danger">
</form>
</div>
                                           
{% endblock bodycontent %}